export enum ErrorMessage {
  Default = 'DEFAULT',
  PLAYLIST_SAVE_DATABASE_EXCEPTION = 'PLAYLIST_SAVE_DATABASE_EXCEPTION',
  ADD_SONG_DATABASE_EXCEPTION = 'ADD_SONG_DATABASE_EXCEPTION',
  GET_PLAYLIST_DATABASE_EXCEPTION = 'GET_PLAYLIST_DATABASE_EXCEPTION',
}
