export enum ErrorMessage {
  Default = 'DEFAULT',
  USER_GET_ONE_DATABASE_EXCEPTION = 'USER_GET_ONE_DATABASE_EXCEPTION',
  USER_SAVE_DATABASE_EXCEPTION = 'USER_SAVE_DATABASE_EXCEPTION',
  USER_UPDATE_DATABASE_EXCEPTION = 'USER_UPDATE_DATABASE_EXCEPTION',
  USER_GET_BY_EMAIL_DATABASE_EXCEPTION = 'USER_GET_BY_EMAIL_DATABASE_EXCEPTION',
  EMAIL_NOT_REGISTERED_EXCEPTION = 'EMAIL_NOT_REGISTERED_EXCEPTION',
}
