export enum ErrorMessage {
  Default = 'DEFAULT',
  USER_GET_ONE_DATABASE_EXCEPTION = 'USER_GET_ONE_DATABASE_EXCEPTION',
  USER_SAVE_DATABASE_EXCEPTION = 'USER_SAVE_DATABASE_EXCEPTION',
  USER_UPDATE_DATABASE_EXCEPTION = 'USER_UPDATE_DATABASE_EXCEPTION',
}
