export enum ErrorMessage {
  Default = 'DEFAULT',
  SONG_SAVE_DATABASE_EXCEPTION = 'SONG_SAVE_DATABASE_EXCEPTION',
  SONG_VALIDATION_EXCEPTION = 'SONG_VALIDATION_EXCEPTION',
  SONG_FILE_SYSTEM_EXCEPTION = 'SONG_FILE_SYSTEM_EXCEPTION',
  SONG_STREAM_EXCEPTION = 'SONG_STREAM_EXCEPTION',
}
